---
title: "Cancer Analysis"
author: "Joseph Lee (sl5nj), Umar Abushaban (uba6z), William Cull (wjc5rt)"
date: "2/1/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
#Load libraries
#library(e1071)
library(tidyverse)
library(plotly)
library(htmltools)
library(devtools)
library(caret)
library(NbClust)
library(randomForest)
library(ggplot2)

```

Reading in the Data
```{r}
#cancer = read.csv("~/Dev/DS4002/4002_handsOn/project1/cancer_analysis/cancer.csv")
cancer = read.csv("./cancer.csv")
```

Cleaning up the data
```{r}
#Remove the last "x" column
cancer = cancer[, -c(33)]

#Convert the diagnosis variable to a factor
cancer[2] = as.factor(cancer$diagnosis)

```

Testing a Graph
```{r}
ggplot(cancer, aes(x=diagnosis, y=radius_mean)) +
  geom_point()
```

```{r}

set.seed(1891)
library(readr)

cancer$diagnosis[cancer$diagnosis == "M"] <- 2
cancer$diagnosis[cancer$diagnosis == "B"] <- 1

cancer$diagnosis <- as.numeric(cancer$diagnosis) 

```


```{r}
table(cancer$diagnosis)

summary(cancer[c("radius_mean","smoothness_mean","compactness_mean")])

```

```{r}

library(corrplot)
library(corrr)
library(ggplot2)

cor1 <- cor(x = cancer$diagnosis, y = cancer[2:19], use="complete.obs")
corrplot(cor1, tl.srt = 25)

```



```{r}

radius_d <- density(cancer$radius_mean)

plot(radius_d)

smoothness_d <- density(cancer$smoothness_mean)

plot(smoothness_d)

compactness_d <- density(cancer$compactness_mean)

plot(compactness_d)
```



#feature scaling
```{r}
# normalization must occur given different scales, kNN is distance based, and metrics are not gaussian in dist.

normalize <- function(x) {
  return ((x- min(x))/ (max(x)- min(x)))
}

cancer_norm <- as.data.frame(lapply(cancer[2:19], normalize))

summary(cancer_norm$radius_mean)
# looks normalized

```

```{r}

# next comes training and model


```



